/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Class.File;
import Class.Employee;
import java.util.*;
import java.lang.String;
/**
 *
 * @author 63909
 */
public class ProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     * @param employeeID
     */
    public ProfilePage(String employeeID) {
        initComponents();
        ArrayList<String> employeeList = new ArrayList<>();
        HashMap<String,String[]> employeeMap = new HashMap<String,String[]>();
        
        jLabelUsername.setText(employeeID);
        jButtonSave.setVisible(false);
        
        File employeeFile = new File();
        employeeFile.setFilePath("src/MotorPH Employee Data - Employee Details.csv");
        employeeList = employeeFile.readFile("src/MotorPH Employee Data - Employee Details.csv");
        
        Employee employee = new Employee();
        employee.setEmployeerMap(employeeList);
        String[] employeeInfo = employee.getEmployeeMap().get(employeeID);
        String[] Birthdate = employeeInfo[3].split("/");        
        jLabelEmployeeName.setText(employeeInfo[1] + " " + employeeInfo[2]);
        
        jTextFieldAddress.setText(employeeInfo[4]);
        jTextFieldBasicSalary.setText(employeeInfo[13]);
        jTextFieldBirthDay.setText(Birthdate[1]);
        jTextFieldBirthMonth.setText(Birthdate[0]);
        jTextFieldBirthYear.setText(Birthdate[2]);
        jTextFieldClothingAllowance.setText(employeeInfo[16]);
        jTextFieldEmployeeID.setText(employeeInfo[0]);
        jTextFieldFirstName.setText(employeeInfo[2]);
        jTextFieldGrossSemimonthlyRate.setText(employeeInfo[17]);
        jTextFieldHourlyRate.setText(employeeInfo[18]);
        jTextFieldImmediateSupervisor.setText(employeeInfo[12]);
        jTextFieldLastName.setText(employeeInfo[1]);
        jTextFieldPagibigID.setText(employeeInfo[9]);
        jTextFieldPhilhealthID.setText(employeeInfo[7]);
        jTextFieldPhoneAllowance.setText(employeeInfo[15]);
        jTextFieldPhoneNumber.setText(employeeInfo[5]);
        jTextFieldPosition.setText(employeeInfo[11]);
        jTextFieldRiceSubsidy.setText(employeeInfo[14]);
        jTextFieldSSSID.setText(employeeInfo[6]);
        jTextFieldStatus.setText(employeeInfo[10]);
        jTextFieldTINID.setText(employeeInfo[8]);
    }

    private ProfilePage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelPersonal = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jLabelFirstNAme = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jTextFieldBirthMonth = new javax.swing.JTextField();
        jLabelBirthMonth = new javax.swing.JLabel();
        jLabelSlash1 = new javax.swing.JLabel();
        jTextFieldBirthDay = new javax.swing.JTextField();
        jLabelSlash2 = new javax.swing.JLabel();
        jLabelBirthDay = new javax.swing.JLabel();
        jTextFieldBirthYear = new javax.swing.JTextField();
        jLabelBirthYear = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelGovermentID = new javax.swing.JLabel();
        jLabelSSSID = new javax.swing.JLabel();
        jTextFieldSSSID = new javax.swing.JTextField();
        jLabelPhilhealthID = new javax.swing.JLabel();
        jTextFieldPhilhealthID = new javax.swing.JTextField();
        jLabelTINID = new javax.swing.JLabel();
        jTextFieldTINID = new javax.swing.JTextField();
        jLabelPagibigID = new javax.swing.JLabel();
        jTextFieldPagibigID = new javax.swing.JTextField();
        jLabelJobDetails = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jTextFieldEmployeeID = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabelPosition = new javax.swing.JLabel();
        jLabelImmediateSupervisor = new javax.swing.JLabel();
        jTextFieldImmediateSupervisor = new javax.swing.JTextField();
        jLabelSalaryDetails = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jTextFieldBasicSalary = new javax.swing.JTextField();
        jLabelRiceSubsidy = new javax.swing.JLabel();
        jTextFieldRiceSubsidy = new javax.swing.JTextField();
        jLabelPhoneAllowance = new javax.swing.JLabel();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jLabelClothingAllowance = new javax.swing.JLabel();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jLabelGrossSemimonthlyRate = new javax.swing.JLabel();
        jTextFieldGrossSemimonthlyRate = new javax.swing.JTextField();
        jLabelHourlyRate = new javax.swing.JLabel();
        jTextFieldHourlyRate = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPh - ProfilePage");

        jLabelEmployeeName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEmployeeName.setText("jLabel1");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUsername.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelEmployeeName))
                .addContainerGap(723, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelEmployeeName)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabelPersonal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPersonal.setText("Personal");

        jLabelFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFullName.setText("Full Name:");

        jTextFieldLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldLastName.setEnabled(false);
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });

        jTextFieldFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFirstName.setEnabled(false);

        jLabelLastName.setText("Last Name");

        jLabelFirstNAme.setText("First Name");

        jLabelBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthdate.setText("Birthdate:");

        jTextFieldBirthMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthMonth.setEnabled(false);

        jLabelBirthMonth.setText("MM");

        jLabelSlash1.setText("/");

        jTextFieldBirthDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthDay.setEnabled(false);

        jLabelSlash2.setText("/");

        jLabelBirthDay.setText("DD");

        jTextFieldBirthYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthYear.setEnabled(false);

        jLabelBirthYear.setText("YYYY");

        jLabelAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress.setText("Address:");

        jTextFieldAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAddress.setEnabled(false);

        jLabelPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number:");

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNumber.setEnabled(false);

        jLabelGovermentID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGovermentID.setText("Goverment ID");

        jLabelSSSID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSSSID.setText("SSS #:");

        jTextFieldSSSID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSSSID.setEnabled(false);

        jLabelPhilhealthID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhilhealthID.setText("Philhealth #:");

        jTextFieldPhilhealthID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhilhealthID.setEnabled(false);

        jLabelTINID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTINID.setText("TIN #:");

        jTextFieldTINID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTINID.setEnabled(false);

        jLabelPagibigID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPagibigID.setText("Pag-ibig #:");

        jTextFieldPagibigID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPagibigID.setEnabled(false);

        jLabelJobDetails.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelJobDetails.setText("Job Details");

        jLabelEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmployeeID.setText("Employee ID:");

        jTextFieldEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmployeeID.setEnabled(false);

        jTextFieldStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldStatus.setEnabled(false);

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelStatus.setText("Status:");

        jTextFieldPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPosition.setEnabled(false);

        jLabelPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPosition.setText("Position:");

        jLabelImmediateSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelImmediateSupervisor.setText("Immediate Supervisor:");

        jTextFieldImmediateSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldImmediateSupervisor.setEnabled(false);

        jLabelSalaryDetails.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSalaryDetails.setText("Salary Details");

        jLabelBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBasicSalary.setText("Basic Salary:");

        jTextFieldBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBasicSalary.setEnabled(false);

        jLabelRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRiceSubsidy.setText("Rice Subsidy:");

        jTextFieldRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldRiceSubsidy.setEnabled(false);

        jLabelPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhoneAllowance.setText("Phone Allowance:");

        jTextFieldPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhoneAllowance.setEnabled(false);

        jLabelClothingAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelClothingAllowance.setText("Clothing Allowance:");

        jTextFieldClothingAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldClothingAllowance.setEnabled(false);

        jLabelGrossSemimonthlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGrossSemimonthlyRate.setText("Gross Semi-monthly Rate:");

        jTextFieldGrossSemimonthlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldGrossSemimonthlyRate.setEnabled(false);

        jLabelHourlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHourlyRate.setText("Hourly Rate:");

        jTextFieldHourlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldHourlyRate.setEnabled(false);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelHourlyRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelGrossSemimonthlyRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldGrossSemimonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPersonal)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelGovermentID)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelPosition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelImmediateSupervisor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldImmediateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelPhilhealthID)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldPhilhealthID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelSSSID)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldSSSID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelPagibigID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPagibigID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelTINID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTINID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelEmployeeID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelPhoneAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelClothingAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelRiceSubsidy)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelBasicSalary)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(5, 5, 5))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelJobDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSalaryDetails)
                                .addGap(152, 152, 152)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabelLastName)
                                .addGap(106, 106, 106)
                                .addComponent(jLabelFirstNAme))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFullName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAddress)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBirthdate)
                    .addComponent(jLabelPhoneNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelBirthMonth))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSlash1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelBirthDay))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSlash2)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelBirthYear))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersonal)
                    .addComponent(jButtonEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelFullName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelFirstNAme))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddress)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBirthdate)
                                    .addComponent(jTextFieldBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSlash1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBirthMonth))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBirthYear))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSlash2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBirthDay)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhoneNumber)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabelGovermentID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSSSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSSSID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPhilhealthID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhilhealthID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTINID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTINID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPagibigID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPagibigID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelJobDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmployeeID)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSalaryDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBasicSalary)
                            .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRiceSubsidy)
                        .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhoneAllowance)
                        .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPosition))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldImmediateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelClothingAllowance)
                        .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImmediateSupervisor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrossSemimonthlyRate)
                    .addComponent(jTextFieldGrossSemimonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHourlyRate)
                    .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        jButtonSave.setVisible(true);
        
        jTextFieldAddress.enable(true);
        jTextFieldBasicSalary.enable(true);
        jTextFieldBirthDay.enable(true);
        jTextFieldBirthMonth.enable(true);
        jTextFieldBirthYear.enable(true);
        jTextFieldClothingAllowance.enable(true);
        jTextFieldEmployeeID.enable(true);;
        jTextFieldFirstName.enable(true);
        jTextFieldGrossSemimonthlyRate.enable(true);
        jTextFieldHourlyRate.enable(true);
        jTextFieldImmediateSupervisor.enable(true);
        jTextFieldLastName.enable(true);
        jTextFieldPagibigID.enable(true);
        jTextFieldPhilhealthID.enable(true);
        jTextFieldPhoneAllowance.enable(true);
        jTextFieldPhoneNumber.enable(true);
        jTextFieldPosition.enable(true);
        jTextFieldRiceSubsidy.enable(true);
        jTextFieldSSSID.enable(true);
        jTextFieldStatus.enable(true);
        jTextFieldTINID.enable(true);
        
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        jButtonSave.setVisible(false);
        
        jTextFieldAddress.enable(false);
        jTextFieldBasicSalary.enable(false);
        jTextFieldBirthDay.enable(false);
        jTextFieldBirthMonth.enable(false);
        jTextFieldBirthYear.enable(false);
        jTextFieldClothingAllowance.enable(false);
        jTextFieldEmployeeID.enable(false);
        jTextFieldFirstName.enable(false);
        jTextFieldGrossSemimonthlyRate.enable(false);
        jTextFieldHourlyRate.enable(false);
        jTextFieldImmediateSupervisor.enable(false);
        jTextFieldLastName.enable(false);        
        jTextFieldPagibigID.enable(false);
        jTextFieldPhilhealthID.enable(false);
        jTextFieldPhoneAllowance.enable(false);
        jTextFieldPhoneNumber.enable(false);
        jTextFieldPosition.enable(false);
        jTextFieldRiceSubsidy.enable(false);
        jTextFieldSSSID.enable(false);
        jTextFieldStatus.enable(false);
        jTextFieldTINID.enable(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBirthDay;
    private javax.swing.JLabel jLabelBirthMonth;
    private javax.swing.JLabel jLabelBirthYear;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelClothingAllowance;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelFirstNAme;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelGovermentID;
    private javax.swing.JLabel jLabelGrossSemimonthlyRate;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelImmediateSupervisor;
    private javax.swing.JLabel jLabelJobDetails;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPagibigID;
    private javax.swing.JLabel jLabelPersonal;
    private javax.swing.JLabel jLabelPhilhealthID;
    private javax.swing.JLabel jLabelPhoneAllowance;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelRiceSubsidy;
    private javax.swing.JLabel jLabelSSSID;
    private javax.swing.JLabel jLabelSalaryDetails;
    private javax.swing.JLabel jLabelSlash1;
    private javax.swing.JLabel jLabelSlash2;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTINID;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBasicSalary;
    private javax.swing.JTextField jTextFieldBirthDay;
    private javax.swing.JTextField jTextFieldBirthMonth;
    private javax.swing.JTextField jTextFieldBirthYear;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldEmployeeID;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGrossSemimonthlyRate;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldImmediateSupervisor;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPagibigID;
    private javax.swing.JTextField jTextFieldPhilhealthID;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldRiceSubsidy;
    private javax.swing.JTextField jTextFieldSSSID;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTINID;
    // End of variables declaration//GEN-END:variables
}
