/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Class.File;
import Class.Employee;
import java.util.*;
import java.lang.String;
/**
 *
 * @author 63909
 */
public class ProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     * @param userInfo
     */
    public ProfilePage(String[] userInfo) {
        initComponents();
        ArrayList<String[]> employeeList = new ArrayList<>();
        HashMap<String,String[]> employeeMap = new HashMap<String,String[]>();
        
        jLabelUsername.setText(userInfo[2]);
        jButtonSave.setVisible(false);
        
        File employeeFile = new File();
        employeeFile.setFilePath("src/MotorPH Employee Data - Employee Details.csv");
        employeeList = employeeFile.readFile("src/MotorPH Employee Data - Employee Details.csv");
        
        Employee employee = new Employee();
        employee.setEmployeerMap(employeeList);
        String[] employeeInfo = employee.getEmployeeMap().get(userInfo[1]);
        
        for (int i = 0; i < employeeInfo.length; i++) {
            employeeInfo[i] = employeeInfo[i].replace("\"", "");
        }
        
        String[] Birthdate = employeeInfo[3].split("/");        
        jLabelEmployeeName.setText(employeeInfo[1] + " " + employeeInfo[2]);
        
        jTextFieldAddress.setText(employeeInfo[4]);
        jTextFieldBasicSalary.setText(employeeInfo[13]);
        jTextFieldBirthDay.setText(Birthdate[1]);
        jTextFieldBirthMonth.setText(Birthdate[0]);
        jTextFieldBirthYear.setText(Birthdate[2]);
        jTextFieldClothingAllowance.setText(employeeInfo[16]);
        jTextFieldEmployeeID.setText(employeeInfo[0]);
        jTextFieldFirstName.setText(employeeInfo[2]);
        jTextFieldGrossSemimonthlyRate.setText(employeeInfo[17]);
        jTextFieldHourlyRate.setText(employeeInfo[18]);
        jTextFieldImmediateSupervisor.setText(employeeInfo[12]);
        jTextFieldLastName.setText(employeeInfo[1]);
        jTextFieldPagibigID.setText(employeeInfo[9]);
        jTextFieldPhilhealthID.setText(employeeInfo[7]);
        jTextFieldPhoneAllowance.setText(employeeInfo[15]);
        jTextFieldPhoneNumber.setText(employeeInfo[5]);
        jTextFieldPosition.setText(employeeInfo[11]);
        jTextFieldRiceSubsidy.setText(employeeInfo[14]);
        jTextFieldSSSID.setText(employeeInfo[6]);
        jTextFieldStatus.setText(employeeInfo[10]);
        jTextFieldTINID.setText(employeeInfo[8]);
    }

    private ProfilePage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLookUpEmployeeID = new javax.swing.JLabel();
        jTextFieldLookUpEmployeeID = new javax.swing.JTextField();
        jButtonLogOut = new javax.swing.JButton();
        jScrollPaneEmployeeInformation = new javax.swing.JScrollPane();
        jPanelEmployeeInformation = new javax.swing.JPanel();
        jPanelPeronal = new javax.swing.JPanel();
        jLabelPersonal = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jLabelFirstNAme = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jTextFieldBirthMonth = new javax.swing.JTextField();
        jLabelBirthMonth = new javax.swing.JLabel();
        jLabelSlash1 = new javax.swing.JLabel();
        jTextFieldBirthDay = new javax.swing.JTextField();
        jLabelSlash2 = new javax.swing.JLabel();
        jLabelBirthDay = new javax.swing.JLabel();
        jTextFieldBirthYear = new javax.swing.JTextField();
        jLabelBirthYear = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jPanelGovernment = new javax.swing.JPanel();
        jLabelGovermentID = new javax.swing.JLabel();
        jLabelSSSID = new javax.swing.JLabel();
        jTextFieldSSSID = new javax.swing.JTextField();
        jLabelPhilhealthID = new javax.swing.JLabel();
        jTextFieldPhilhealthID = new javax.swing.JTextField();
        jLabelTINID = new javax.swing.JLabel();
        jTextFieldTINID = new javax.swing.JTextField();
        jLabelPagibigID = new javax.swing.JLabel();
        jTextFieldPagibigID = new javax.swing.JTextField();
        jPanelJob = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabelPosition = new javax.swing.JLabel();
        jLabelImmediateSupervisor = new javax.swing.JLabel();
        jTextFieldImmediateSupervisor = new javax.swing.JTextField();
        jLabelJob = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jTextFieldEmployeeID = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jPanelSalary = new javax.swing.JPanel();
        jLabelSalary = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jTextFieldBasicSalary = new javax.swing.JTextField();
        jLabelRiceSubsidy = new javax.swing.JLabel();
        jTextFieldRiceSubsidy = new javax.swing.JTextField();
        jLabelPhoneAllowance = new javax.swing.JLabel();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jLabelClothingAllowance = new javax.swing.JLabel();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jLabelGrossSemimonthlyRate = new javax.swing.JLabel();
        jTextFieldGrossSemimonthlyRate = new javax.swing.JTextField();
        jLabelHourlyRate = new javax.swing.JLabel();
        jTextFieldHourlyRate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButtonCalculateSalary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPh - ProfilePage");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelEmployeeName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEmployeeName.setText("jLabel1");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUsername.setText("jLabel2");

        jLabelLookUpEmployeeID.setText("Employee ID");

        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelLookUpEmployeeID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldLookUpEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelEmployeeName))
                .addGap(128, 128, 128)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEmployeeName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelUsername)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldLookUpEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLookUpEmployeeID)
                .addGap(30, 30, 30))
        );

        jLabelPersonal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPersonal.setText("Personal");

        jLabelFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFullName.setText("Full Name:");

        jTextFieldLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldLastName.setEnabled(false);

        jTextFieldFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFirstName.setEnabled(false);

        jLabelLastName.setText("Last Name");

        jLabelFirstNAme.setText("First Name");

        jLabelBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBirthdate.setText("Birthdate:");

        jTextFieldBirthMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthMonth.setEnabled(false);

        jLabelBirthMonth.setText("MM");

        jLabelSlash1.setText("/");

        jTextFieldBirthDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthDay.setEnabled(false);

        jLabelSlash2.setText("/");

        jLabelBirthDay.setText("DD");

        jTextFieldBirthYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBirthYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBirthYear.setEnabled(false);

        jLabelBirthYear.setText("YYYY");

        jLabelAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress.setText("Address:");

        jTextFieldAddress.setEditable(false);
        jTextFieldAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAddress.setEnabled(false);

        jLabelPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number:");

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNumber.setEnabled(false);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPeronalLayout = new javax.swing.GroupLayout(jPanelPeronal);
        jPanelPeronal.setLayout(jPanelPeronalLayout);
        jPanelPeronalLayout.setHorizontalGroup(
            jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPeronalLayout.createSequentialGroup()
                        .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddress)
                            .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelPersonal))
                                .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabelFullName))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeronalLayout.createSequentialGroup()
                                        .addComponent(jLabelBirthdate)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabelBirthMonth)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabelBirthDay)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabelBirthYear))
                                            .addComponent(jTextFieldBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPeronalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit))))
                    .addGroup(jPanelPeronalLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabelLastName)
                        .addGap(106, 106, 106)
                        .addComponent(jLabelFirstNAme)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPeronalLayout.createSequentialGroup()
                    .addContainerGap(545, Short.MAX_VALUE)
                    .addComponent(jLabelPhoneNumber)
                    .addGap(59, 59, 59)
                    .addComponent(jLabelSlash1)
                    .addGap(47, 47, 47)
                    .addComponent(jLabelSlash2)
                    .addGap(62, 62, 62)))
        );
        jPanelPeronalLayout.setVerticalGroup(
            jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeronalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersonal)
                    .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSave)
                        .addComponent(jButtonEdit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFullName)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelFirstNAme)
                    .addComponent(jLabelBirthDay)
                    .addComponent(jLabelBirthMonth)
                    .addComponent(jLabelBirthYear))
                .addGap(18, 18, 18)
                .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPeronalLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(jPanelPeronalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelSlash1)
                        .addComponent(jLabelSlash2))
                    .addGap(47, 47, 47)
                    .addComponent(jLabelPhoneNumber)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelGovermentID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGovermentID.setText("Government ID");

        jLabelSSSID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSSSID.setText("SSS #:");

        jTextFieldSSSID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSSSID.setEnabled(false);

        jLabelPhilhealthID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhilhealthID.setText("Philhealth #:");

        jTextFieldPhilhealthID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhilhealthID.setEnabled(false);

        jLabelTINID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTINID.setText("TIN #:");

        jTextFieldTINID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTINID.setEnabled(false);

        jLabelPagibigID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPagibigID.setText("Pag-ibig #:");

        jTextFieldPagibigID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPagibigID.setEnabled(false);

        javax.swing.GroupLayout jPanelGovernmentLayout = new javax.swing.GroupLayout(jPanelGovernment);
        jPanelGovernment.setLayout(jPanelGovernmentLayout);
        jPanelGovernmentLayout.setHorizontalGroup(
            jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelGovernmentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGovernmentLayout.createSequentialGroup()
                                .addComponent(jLabelPhilhealthID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPhilhealthID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGovernmentLayout.createSequentialGroup()
                                .addComponent(jLabelSSSID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSSSID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGovernmentLayout.createSequentialGroup()
                            .addComponent(jLabelPagibigID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPagibigID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGovernmentLayout.createSequentialGroup()
                            .addComponent(jLabelTINID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldTINID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelGovernmentLayout.createSequentialGroup()
                            .addComponent(jLabelGovermentID)
                            .addGap(149, 149, 149)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelGovernmentLayout.setVerticalGroup(
            jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelGovernmentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelGovermentID)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldSSSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSSSID))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPhilhealthID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhilhealthID))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldTINID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTINID))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelGovernmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPagibigID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPagibigID))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelStatus.setText("Status:");

        jTextFieldPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPosition.setEnabled(false);

        jLabelPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPosition.setText("Position:");

        jLabelImmediateSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelImmediateSupervisor.setText("Immediate Supervisor:");

        jTextFieldImmediateSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldImmediateSupervisor.setEnabled(false);

        jLabelJob.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelJob.setText("Job");

        jLabelEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmployeeID.setText("Employee ID:");

        jTextFieldEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmployeeID.setEnabled(false);

        jTextFieldStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldStatus.setEnabled(false);

        javax.swing.GroupLayout jPanelJobLayout = new javax.swing.GroupLayout(jPanelJob);
        jPanelJob.setLayout(jPanelJobLayout);
        jPanelJobLayout.setHorizontalGroup(
            jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelJobLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJobLayout.createSequentialGroup()
                            .addComponent(jLabelStatus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJobLayout.createSequentialGroup()
                            .addComponent(jLabelPosition)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJobLayout.createSequentialGroup()
                            .addComponent(jLabelImmediateSupervisor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldImmediateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJobLayout.createSequentialGroup()
                            .addComponent(jLabelEmployeeID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelJobLayout.createSequentialGroup()
                            .addComponent(jLabelJob)
                            .addGap(182, 182, 182)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelJobLayout.setVerticalGroup(
            jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelJobLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelJob)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmployeeID))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStatus))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPosition))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldImmediateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelImmediateSupervisor))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabelSalary.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSalary.setText("Salary");

        jLabelBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBasicSalary.setText("Basic Salary:");

        jTextFieldBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBasicSalary.setEnabled(false);

        jLabelRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRiceSubsidy.setText("Rice Subsidy:");

        jTextFieldRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldRiceSubsidy.setEnabled(false);

        jLabelPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhoneAllowance.setText("Phone Allowance:");

        jTextFieldPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPhoneAllowance.setEnabled(false);

        jLabelClothingAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelClothingAllowance.setText("Clothing Allowance:");

        jTextFieldClothingAllowance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldClothingAllowance.setEnabled(false);

        jLabelGrossSemimonthlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGrossSemimonthlyRate.setText("Gross Semi-monthly Rate:");

        jTextFieldGrossSemimonthlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldGrossSemimonthlyRate.setEnabled(false);

        jLabelHourlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHourlyRate.setText("Hourly Rate:");

        jTextFieldHourlyRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldHourlyRate.setEnabled(false);

        javax.swing.GroupLayout jPanelSalaryLayout = new javax.swing.GroupLayout(jPanelSalary);
        jPanelSalary.setLayout(jPanelSalaryLayout);
        jPanelSalaryLayout.setHorizontalGroup(
            jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalaryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelSalaryLayout.createSequentialGroup()
                            .addComponent(jLabelHourlyRate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSalaryLayout.createSequentialGroup()
                            .addComponent(jLabelGrossSemimonthlyRate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldGrossSemimonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalaryLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalaryLayout.createSequentialGroup()
                                        .addComponent(jLabelPhoneAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalaryLayout.createSequentialGroup()
                                        .addComponent(jLabelClothingAllowance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalaryLayout.createSequentialGroup()
                                        .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelSalaryLayout.createSequentialGroup()
                                                .addComponent(jLabelRiceSubsidy)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelSalaryLayout.createSequentialGroup()

                                                .addComponent(jLabelBasicSalary)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(5, 5, 5))))
                            .addGroup(jPanelSalaryLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelSalary)
                                .addGap(152, 152, 152))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelSalaryLayout.setVerticalGroup(
            jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
            .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalaryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelSalary)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBasicSalary)
                        .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRiceSubsidy)
                        .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPhoneAllowance)
                        .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClothingAllowance)
                        .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGrossSemimonthlyRate)
                        .addComponent(jTextFieldGrossSemimonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHourlyRate)
                        .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelEmployeeInformationLayout = new javax.swing.GroupLayout(jPanelEmployeeInformation);
        jPanelEmployeeInformation.setLayout(jPanelEmployeeInformationLayout);
        jPanelEmployeeInformationLayout.setHorizontalGroup(
            jPanelEmployeeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmployeeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPeronal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEmployeeInformationLayout.createSequentialGroup()
                        .addComponent(jPanelGovernment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanelEmployeeInformationLayout.setVerticalGroup(
            jPanelEmployeeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPeronal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelEmployeeInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGovernment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jScrollPaneEmployeeInformation.setViewportView(jPanelEmployeeInformation);

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonCalculateSalary.setBackground(new java.awt.Color(242, 242, 242));
        jButtonCalculateSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll.png"))); // NOI18N


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalculateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneEmployeeInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEmployeeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCalculateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        jButtonEdit.setVisible(true);
        jButtonSave.setVisible(false);

        jPanelEmployeeInformation.requestFocus();
        jPanelPeronal.requestFocus();
        jTextFieldAddress.enable(false);
        jTextFieldBasicSalary.enable(false);
        jTextFieldBirthDay.enable(false);
        jTextFieldBirthMonth.enable(false);
        jTextFieldBirthYear.enable(false);
        jTextFieldClothingAllowance.enable(false);
        jTextFieldEmployeeID.enable(false);
        jTextFieldFirstName.enable(false);
        jTextFieldGrossSemimonthlyRate.enable(false);
        jTextFieldHourlyRate.enable(false);
        jTextFieldImmediateSupervisor.enable(false);
        jTextFieldLastName.enable(false);
        jTextFieldPagibigID.enable(false);
        jTextFieldPhilhealthID.enable(false);
        jTextFieldPhoneAllowance.enable(false);
        jTextFieldPhoneNumber.enable(false);
        jTextFieldPosition.enable(false);
        jTextFieldRiceSubsidy.enable(false);
        jTextFieldSSSID.enable(false);
        jTextFieldStatus.enable(false);
        jTextFieldTINID.enable(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        jButtonEdit.setVisible(false);
        jButtonSave.setVisible(true);

        jTextFieldAddress.enable(true);
        jTextFieldBasicSalary.enable(true);
        jTextFieldBirthDay.enable(true);
        jTextFieldBirthMonth.enable(true);
        jTextFieldBirthYear.enable(true);
        jTextFieldClothingAllowance.enable(true);
        jTextFieldEmployeeID.enable(true);
        jTextFieldFirstName.enable(true);
        jTextFieldGrossSemimonthlyRate.enable(true);
        jTextFieldHourlyRate.enable(true);
        jTextFieldImmediateSupervisor.enable(true);
        jTextFieldLastName.enable(true);
        jTextFieldPagibigID.enable(true);
        jTextFieldPhilhealthID.enable(true);
        jTextFieldPhoneAllowance.enable(true);
        jTextFieldPhoneNumber.enable(true);
        jTextFieldPosition.enable(true);
        jTextFieldRiceSubsidy.enable(true);
        jTextFieldSSSID.enable(true);
        jTextFieldStatus.enable(true);
        jTextFieldTINID.enable(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        EmployeeListPage employeeListPage = new EmployeeListPage();
//            employeeListPage.setVisible(true);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCalculateSalary;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBirthDay;
    private javax.swing.JLabel jLabelBirthMonth;
    private javax.swing.JLabel jLabelBirthYear;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelClothingAllowance;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelFirstNAme;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelGovermentID;
    private javax.swing.JLabel jLabelGrossSemimonthlyRate;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelImmediateSupervisor;
    private javax.swing.JLabel jLabelJob;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLookUpEmployeeID;
    private javax.swing.JLabel jLabelPagibigID;
    private javax.swing.JLabel jLabelPersonal;
    private javax.swing.JLabel jLabelPhilhealthID;
    private javax.swing.JLabel jLabelPhoneAllowance;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelRiceSubsidy;
    private javax.swing.JLabel jLabelSSSID;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JLabel jLabelSlash1;
    private javax.swing.JLabel jLabelSlash2;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTINID;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEmployeeInformation;
    private javax.swing.JPanel jPanelGovernment;
    private javax.swing.JPanel jPanelJob;
    private javax.swing.JPanel jPanelPeronal;
    private javax.swing.JPanel jPanelSalary;
    private javax.swing.JScrollPane jScrollPaneEmployeeInformation;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBasicSalary;
    private javax.swing.JTextField jTextFieldBirthDay;
    private javax.swing.JTextField jTextFieldBirthMonth;
    private javax.swing.JTextField jTextFieldBirthYear;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldEmployeeID;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGrossSemimonthlyRate;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldImmediateSupervisor;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldLookUpEmployeeID;
    private javax.swing.JTextField jTextFieldPagibigID;
    private javax.swing.JTextField jTextFieldPhilhealthID;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldRiceSubsidy;
    private javax.swing.JTextField jTextFieldSSSID;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTINID;
    // End of variables declaration//GEN-END:variables
}
